config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers, only: :create
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description, length: { minimum: 50 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  validates :title, length: { minimum: 40 }
  validates :description, length: { minimum: 150 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    if @answer.save
      flash[:notice] = "Comment Saved!"
      redirect_to @question
    else
      flash.now[:notice] = "Invalid answer!  Please try again."
      redirect_to @question
    end
  end

  private
  def answer_params
    results = params.require(:answer).permit(:description)
    results[:question_id] = params[:question_id]
    results
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "Question successfully submitted!"
      redirect_to questions_path
    else
      flash[:notice] = "Invalid input, please try again!"
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to question_path(@question)
    else
      flash[:notice] = "Invalid input, please try again!"
      redirect_to edit_question_path(@question)
    end
  end

    def destroy
    @question = Question.find(params[:id])
    @question.answers.each do |answer|
      answer.destroy
    end
    if @question.destroy
      flash[:notice] = "This question was removed."
      redirect_to questions_path
    else
      render :show
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash.any? %>
    <div>
      <%= flash[:notice] %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h1>Edit this question:</h1>
<%= form_for @question do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<ul>
  <% @questions.each do |question| %>
    <li> <%= link_to "#{question.title}", question_path(question) %><br>
      <%= question.description %></li>
      <hr>
  <% end %>
</ul>

<div>
<%= link_to "Post a new question", new_question_path %>
</div>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<h3><%= @question.title %></h3><br>
<div><%= @question.description %></div><br>

<h3>Provide an answer:</h3>
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :description %>
  <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>

<h3>Submitted Answers:</h3>
<ul>
  <% @question.answers.order(created_at: :desc).each do |answer| %>
    <li><%= answer.description %></li>
  <% end %>
</ul>

<div>
<%= link_to "Edit this question", edit_question_path %>
</div>

<div>
  <%= link_to 'Delete this question', question_path, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

<div>
<%= link_to "Questions List", questions_path %>
</div>